### ISSUE TITLE
Incorrect URLs generated by gem

### ISSUE THREAD

**Issue by Cri465** [nlpcloud/nlpcloud-ruby#1]
When creating an NLPCloud client and passing in a model, the URL generated has an extra / after 'v1' 

eg.

client = NLPCloud::Client.new("fast-gpt-j", "")

(byebug) client
#<NLPCloud::Client:0x000055fef6e71648 @headers={"Authorization"=>"", "Content-Type"=>"application/json", "User-Agent"=>"nlpcloud-ruby-client"}, @root_url="https://api.nlpcloud.io/v1//fast-gpt-j">

Seems to be the conditional checking for 'lang', the default empty string provided in initialize resolves to true

**Comment by juliensalinas** [comment]
Hello @Cri465 thanks so much for reporting this, and sorry about this glitch.
We just fixed it!
Could you please try the latest version and let me know if it is all good now on your end?

**Comment by Cri465** [comment]
All seems well now thank you!

**Comment by juliensalinas** [comment]
Ok perfect 👍🏻
