### ISSUE TITLE
Question: Which models can be used to generate embeddings?

### ISSUE THREAD

**Issue by andreibondarev** [nlpcloud/nlpcloud-ruby#2]
Which models can be used to generate embeddings? I was only able to get "paraphrase-multilingual-mpnet-base-v2" working. Can I use Mistral?

**Comment by juliensalinas** [comment]
Hello @andreibondarev, thank you for your message, 
Yes, paraphrase multilingual mpnet base v2 is our only model for embeddings: https://docs.nlpcloud.com/#embeddings
Unfortunately Mistral is not supported for embeddings for the moment.
Please don't hesitate to ask us more questions!
